version: "3.9"
services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: porssiohjain
      POSTGRES_PASSWORD: porssiohjain
      POSTGRES_DB: porssiohjain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: