### Create account
POST http://localhost:8080/account/create
Content-Type: application/json

### Login into account
POST http://localhost:8080/account/login
Content-Type: application/json

{
  "uuid": "{{uuid}}",
  "secret": "{{secret}}"
}

### Create device for account
POST http://localhost:8080/device/create/1
Content-Type: application/json
Authorization: {{token}}

{
  "deviceName": "Shelly Pro 3"
}

### Create control for account
POST http://localhost:8080/control/create
Content-Type: application/json
Authorization: {{token}}

{
  "accountId": 1,
  "name": "Test control 1",
  "maxPriceSnt": 8.5,
  "dailyOnMinutes": 120
}

### Get all controls for account
GET http://localhost:8080/control/controls
Content-Type: application/json
Authorization: {{token}}

### Link device to control
POST http://localhost:8080/control/1/create/device?deviceId=1&deviceChannel=1
Content-Type: application/json
Authorization: {{token}}


### Get control statuses for device with uuid
GET http://localhost:8080/control/28217a08-df0b-4d21-b2b8-66a321cc6658
Content-Type: application/json

