import { FormEvent, useEffect, useState } from "react";
import AppDialog from "@/components/AppDialog";
import { getCurrentTimezone } from "@/lib/add-device-flow";
import { useI18n } from "@/lib/i18n";
import { createWindNotification, deleteWindNotification, fetchWindForecast, fetchWindNotifications, updateWindNotification, type WindForecast, type WindNotification, type WindRuleType } from "@/lib/wind";

const W=960, H=250, P=42;
const number = (value: number | null, digits=0) => value == null ? "–" : new Intl.NumberFormat(undefined,{maximumFractionDigits:digits}).format(value);

export default function WindForecastCard() {
  const { t } = useI18n("windForecast"); const timezone=getCurrentTimezone();
  const [data,setData]=useState<WindForecast|null>(null), [error,setError]=useState<string|null>(null), [open,setOpen]=useState(false);
  useEffect(()=>{ fetchWindForecast(timezone).then(setData).catch(e=>setError(e instanceof Error?e.message:String(e))); },[]);
  if(error) return <div className="app-card p-6 text-on-error-container">{t("failed")}: {error}</div>;
  if(!data) return <div className="app-card p-6 text-on-surface-variant">{t("loading")}</div>;
  const values=data.points.map(p=>p.megawatts), min=Math.min(...values), max=Math.max(...values), range=max-min||1;
  const path=values.map((v,i)=>`${i?"L":"M"} ${(P+(W-2*P)*i/Math.max(values.length-1,1)).toFixed(1)} ${(P+(H-2*P)*(1-(v-min)/range)).toFixed(1)}`).join(" ");
  return <article className="app-card overflow-hidden p-4 sm:p-5">
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-primary">{t("eyebrow")}</p><h3 className="font-headline text-3xl font-black">{t("title")}</h3><p className="mt-2 text-sm text-on-surface-variant">{t("description",{timezone:data.timezone})}</p></div><button className="secondary-action justify-center px-4 py-2 text-sm" onClick={()=>setOpen(true)}>{t("notifications")}</button></div>
    {values.length ? <div className="overflow-x-auto rounded-3xl bg-surface-container-low p-3"><svg className="min-w-[44rem] w-full" viewBox={`0 0 ${W} ${H}`} role="img" aria-label={t("aria")}><line x1={P} x2={W-P} y1={H-P} y2={H-P} stroke="rgb(var(--color-outline-variant))"/><path d={path} fill="none" stroke="rgb(var(--color-primary))" strokeWidth="4" strokeLinejoin="round"/><text x={P} y={22} fill="rgb(var(--color-on-surface-variant))" fontSize="13">{number(max)} MW</text><text x={P} y={H-8} fill="rgb(var(--color-on-surface-variant))" fontSize="13">{number(min)} MW</text></svg></div> : <p>{t("empty")}</p>}
    <div className="mt-4 grid gap-3 sm:grid-cols-3"><Stat label={t("todayAverage")} value={`${number(data.todayAverage)} MW`}/><Stat label={t("tomorrowAverage")} value={`${number(data.tomorrowAverage)} MW`}/><Stat label={t("drop")} value={data.tomorrowDropPercent==null?"–":`${number(data.tomorrowDropPercent,1)} %`}/></div>
    <WindDialog open={open} close={()=>setOpen(false)} timezone={timezone}/>
  </article>;
}
function Stat({label,value}:{label:string,value:string}) { return <div className="rounded-2xl bg-surface-container p-4"><p className="metric-label mb-2">{label}</p><p className="font-headline text-2xl font-black">{value}</p></div>; }
function WindDialog({open,close,timezone}:{open:boolean;close:()=>void;timezone:string}) {
 const {t}=useI18n("windNotifications"), common=useI18n("common").t; const [items,setItems]=useState<WindNotification[]>([]), [editing,setEditing]=useState<WindNotification|null>(null), [name,setName]=useState(""), [description,setDescription]=useState(""), [rule,setRule]=useState<WindRuleType>("TOMORROW_DROP_PERCENT"), [threshold,setThreshold]=useState("30"), [error,setError]=useState<string|null>(null);
 useEffect(()=>{if(open) fetchWindNotifications().then(setItems).catch(e=>setError(String(e)));},[open]); if(!open)return null;
 const reset=()=>{setEditing(null);setName("");setDescription("");setRule("TOMORROW_DROP_PERCENT");setThreshold("30")};
 const edit=(n:WindNotification)=>{setEditing(n);setName(n.name);setDescription(n.description??"");setRule(n.ruleType);setThreshold(String(n.threshold))};
 async function submit(e:FormEvent){e.preventDefault();try{const payload={name:name.trim(),description:description.trim()||null,ruleType:rule,threshold:Number(threshold),timezone,enabled:true};const saved=editing?await updateWindNotification(editing.id,payload):await createWindNotification(payload);setItems(old=>editing?old.map(x=>x.id===saved.id?saved:x):[...old,saved]);reset()}catch(x){setError(String(x))}}
 return <AppDialog isOpen={open} onClose={close} eyebrow={t("eyebrow")} title={t("title")} description={t("description")} maxWidthClassName="max-w-5xl"><div className="grid gap-5 lg:grid-cols-[1fr_22rem]"><div className="space-y-3">{items.length===0?<p className="rounded-xl bg-surface-container p-4 text-sm">{t("empty")}</p>:items.map(n=><article key={n.id} className="rounded-xl bg-surface-container p-4"><h4 className="font-headline text-lg font-bold">{n.name}</h4><p className="mt-1 text-sm text-on-surface-variant">{t(n.ruleType,{threshold:number(n.threshold,1)})}</p><div className="mt-3 flex gap-2"><button className="secondary-action px-3 py-2 text-xs" onClick={()=>edit(n)}>{common("edit")}</button><button className="secondary-action px-3 py-2 text-xs" onClick={async()=>{await deleteWindNotification(n.id);setItems(x=>x.filter(i=>i.id!==n.id))}}>{common("remove")}</button></div></article>)}</div><form className="rounded-xl bg-surface-container p-4 space-y-4" onSubmit={submit}><h4 className="font-headline text-xl font-bold">{editing?t("edit"):t("add")}</h4><input required className="w-full rounded-t-lg bg-surface-container-highest px-4 py-3" placeholder={t("name")} value={name} onChange={e=>setName(e.target.value)}/><textarea className="w-full rounded-xl bg-surface-container-highest px-4 py-3" placeholder={t("descriptionLabel")} value={description} onChange={e=>setDescription(e.target.value)}/><select className="w-full rounded-t-lg bg-surface-container-highest px-3 py-3" value={rule} onChange={e=>setRule(e.target.value as WindRuleType)}><option value="TOMORROW_DROP_PERCENT">{t("dropRule")}</option><option value="TOMORROW_AVERAGE_BELOW">{t("averageRule")}</option></select><label className="block text-sm font-bold">{rule==="TOMORROW_DROP_PERCENT"?t("percentThreshold"):t("mwThreshold")}<input min="0" required type="number" step="0.1" className="mt-2 w-full rounded-t-lg bg-surface-container-highest px-4 py-3" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label><button className="primary-action w-full justify-center" type="submit">{common("save")}</button>{editing?<button className="secondary-action w-full justify-center" type="button" onClick={reset}>{common("cancel")}</button>:null}</form></div>{error?<p className="mt-4 text-on-error-container">{error}</p>:null}</AppDialog>;
}
