### GET request with a header
GET https://dataportal-api.nordpoolgroup.com/api/DayAheadPriceIndices?currency=EUR&market=DayAhead&indexNames=FI&
    resolutionInMinutes=15&date=2025-10-08
Accept: application/json
Origin: https://data.nordpoolgroup.com